export const SOCKET_ONOPEN = "SOCKET_ONOPEN";
export const SOCKET_ONMESSAGE = "SOCKET_ONMESSAGE";
export const SOCKET_ONCLOSE = "SOCKET_ONCLOSE";

export const CLEAR_TRANSACTIONS = "CLEAR_TRANSACTIONS";
